services:
  redpanda:
    image: redpandadata/redpanda:v25.2.8
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --mode
      - dev-container
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redpanda-data:
